## We Are Create Movie Recommendation System using ML , NLP , TF-IDF & FastAPI

In [77]:
## Import Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [78]:
import warnings
warnings.filterwarnings('ignore')

#### Load TMDB 5000 Thousand Movies Data Sets

In [79]:
credits = pd.read_csv(r"C:\Users\dheer\Desktop\Movies Recommendation\Datasets\tmdb_5000_credits.csv")
movies = pd.read_csv(r"C:\Users\dheer\Desktop\Movies Recommendation\Datasets\tmdb_5000_movies.csv")

In [80]:
credits

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...
4798,9367,El Mariachi,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4799,72766,Newlyweds,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4800,231617,"Signed, Sealed, Delivered","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4801,126186,Shanghai Calling,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4802,25975,My Date with Drew,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [81]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [82]:
## Data Merging Both Credits and Movies Dataset
credits.columns = ['id','tittle','cast','crew']
df= movies.merge(credits,on='id')

In [83]:
df.shape

(4803, 23)

In [84]:
## Check all columns in the dataset
df.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count', 'tittle', 'cast', 'crew'],
      dtype='str')

In [85]:
# Check Data information
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   str
 2   homepage              1712 non-null   str
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   str
 5   original_language     4803 non-null   str
 6   original_title        4803 non-null   str
 7   overview              4800 non-null   str
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   str
 10  production_countries  4803 non-null   str
 11  release_date          4802 non-null   str
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   str
 15  status                4803 non-null   str
 16  tagline               3959 non-null   str
 17  title                 4803 non-null   str
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
 20  tittle                4803 non-null   str
 21  cast                  4803 non-null   str
 22  crew                  4803 non-null   str
dtypes: float64(3), int64(4), str(16)
memory usage: 39.2 MB

In [86]:
## Check for null values in the dataset
df.isnull().sum()

budget                     0
genres                     0
homepage                3091
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
tittle                     0
cast                       0
crew                       0
dtype: int64

In [87]:
df['homepage']

0                             http://www.avatarmovie.com/
1            http://disney.go.com/disneypictures/pirates/
2             http://www.sonypictures.com/movies/spectre/
3                      http://www.thedarkknightrises.com/
4                    http://movies.disney.com/john-carter
                              ...
4798                                                  NaN
4799                                                  NaN
4800    http://www.hallmarkchannel.com/signedsealeddel...
4801                          http://shanghaicalling.com/
4802                                                  NaN
Name: homepage, Length: 4803, dtype: str

In [88]:
## Check Duplicates in the dataset
df.duplicated().sum()

np.int64(0)

In [89]:
## selecting the required columns for the model
df = df[['title', 'overview', 'genres', 'tagline' , 'vote_average', 'popularity']]

In [90]:
df.head()

,title,overview,genres,tagline,vote_average,popularity
0,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",Enter the World of Pandora.,7.2,150.437577
1,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","At the end of the world, the adventure begins.",6.9,139.082615
2,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",A Plan No One Escapes,6.3,107.376788
3,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",The Legend Ends,7.6,112.312950
4,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","Lost in our world, found in another.",6.1,43.926995

In [91]:
# Check the null values in the dataset
df.isnull().sum()

title             0
overview          3
genres            0
tagline         844
vote_average      0
popularity        0
dtype: int64

In [92]:
# Fill the null values in the dataset with empty string
df['overview'] = df['overview'].fillna('')

In [93]:
df.iloc[0]['genres']

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [94]:
# ast.literal_eval() safely converts a string into a Python object 
# (like list, dict, tuple) without using risky eval().
import ast

In [95]:
df['genres'] = df['genres'].apply(lambda x: ' '.join([i['name'] for i in ast.literal_eval(x)]))

In [96]:
df.head()

,title,overview,genres,tagline,vote_average,popularity
0,Avatar,"In the 22nd century, a paraplegic Marine is di...",Action Adventure Fantasy Science Fiction,Enter the World of Pandora.,7.2,150.437577
1,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",Adventure Fantasy Action,"At the end of the world, the adventure begins.",6.9,139.082615
2,Spectre,A cryptic message from Bond’s past sends him o...,Action Adventure Crime,A Plan No One Escapes,6.3,107.376788
3,The Dark Knight Rises,Following the death of District Attorney Harve...,Action Crime Drama Thriller,The Legend Ends,7.6,112.312950
4,John Carter,"John Carter is a war-weary, former military ca...",Action Adventure Science Fiction,"Lost in our world, found in another.",6.1,43.926995

In [97]:
## Fill the null values in the dataset with empty string
df['tagline'] = df['tagline'].fillna('')

In [98]:
df.isnull().sum()

title           0
overview        0
genres          0
tagline         0
vote_average    0
popularity      0
dtype: int64

In [99]:
# Create a new column 'tags' by combining 'overview', 'genres', and 'tagline'
df['tags'] = df['overview'] + ' ' + df['genres'] + ' ' + df['tagline']

In [100]:
df['tags']

0       In the 22nd century, a paraplegic Marine is di...
1       Captain Barbossa, long believed to be dead, ha...
2       A cryptic message from Bond’s past sends him o...
3       Following the death of District Attorney Harve...
4       John Carter is a war-weary, former military ca...
                              ...
4798    El Mariachi just wants to play his guitar and ...
4799    A newlywed couple's honeymoon is upended by th...
4800    "Signed, Sealed, Delivered" introduces a dedic...
4801    When ambitious New York attorney Sam is sent t...
4802    Ever since the second grade when he first saw ...
Name: tags, Length: 4803, dtype: str

In [101]:
df.head()

,title,overview,genres,tagline,vote_average,popularity,tags
0,Avatar,"In the 22nd century, a paraplegic Marine is di...",Action Adventure Fantasy Science Fiction,Enter the World of Pandora.,7.2,150.437577,"In the 22nd century, a paraplegic Marine is di..."
1,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",Adventure Fantasy Action,"At the end of the world, the adventure begins.",6.9,139.082615,"Captain Barbossa, long believed to be dead, ha..."
2,Spectre,A cryptic message from Bond’s past sends him o...,Action Adventure Crime,A Plan No One Escapes,6.3,107.376788,A cryptic message from Bond’s past sends him o...
3,The Dark Knight Rises,Following the death of District Attorney Harve...,Action Crime Drama Thriller,The Legend Ends,7.6,112.312950,Following the death of District Attorney Harve...
4,John Carter,"John Carter is a war-weary, former military ca...",Action Adventure Science Fiction,"Lost in our world, found in another.",6.1,43.926995,"John Carter is a war-weary, former military ca..."

In [102]:
import nltk
import string
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
import re

In [103]:
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\dheer\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\dheer\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [104]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\dheer\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\dheer\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [105]:
stopwords = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

In [106]:
def preprocess_text(text):
    # Convert to lowercase
    text = text.lower()
    
    # Remove punctuation
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    
    # Tokenize the text
    tokens = word_tokenize(text)
    
    # Remove stopwords and lemmatize
    tokens = [lemmatizer.lemmatize(word) for word in tokens if word not in stopwords]
    
    return ' '.join(tokens)

In [107]:
df['tags'] = df['tags'].apply(preprocess_text)

In [108]:
df.head()

,title,overview,genres,tagline,vote_average,popularity,tags
0,Avatar,"In the 22nd century, a paraplegic Marine is di...",Action Adventure Fantasy Science Fiction,Enter the World of Pandora.,7.2,150.437577,22nd century paraplegic marine dispatched moon...
1,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",Adventure Fantasy Action,"At the end of the world, the adventure begins.",6.9,139.082615,captain barbossa long believed dead come back ...
2,Spectre,A cryptic message from Bond’s past sends him o...,Action Adventure Crime,A Plan No One Escapes,6.3,107.376788,cryptic message bond past sends trail uncover ...
3,The Dark Knight Rises,Following the death of District Attorney Harve...,Action Crime Drama Thriller,The Legend Ends,7.6,112.312950,following death district attorney harvey dent ...
4,John Carter,"John Carter is a war-weary, former military ca...",Action Adventure Science Fiction,"Lost in our world, found in another.",6.1,43.926995,john carter warweary former military captain w...

In [109]:
df['tags']

0       22nd century paraplegic marine dispatched moon...
1       captain barbossa long believed dead come back ...
2       cryptic message bond past sends trail uncover ...
3       following death district attorney harvey dent ...
4       john carter warweary former military captain w...
                              ...
4798    el mariachi want play guitar carry family trad...
4799    newlywed couple honeymoon upended arrival resp...
4800    signed sealed delivered introduces dedicated q...
4801    ambitious new york attorney sam sent shanghai ...
4802    ever since second grade first saw et extraterr...
Name: tags, Length: 4803, dtype: str

In [110]:
## Set index of the dataframe to 'title' for easier access
df = df.reset_index(drop=True)

In [111]:
indices = pd.Series(df.index, index=df['title']).drop_duplicates()

indices

title
Avatar                                         0
Pirates of the Caribbean: At World's End       1
Spectre                                        2
The Dark Knight Rises                          3
John Carter                                    4
                                            ...
El Mariachi                                 4798
Newlyweds                                   4799
Signed, Sealed, Delivered                   4800
Shanghai Calling                            4801
My Date with Drew                           4802
Length: 4803, dtype: int64

## Vectorization using TF-IDF Vectorizer

In [114]:
from sklearn.feature_extraction.text import CountVectorizer

In [115]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [118]:
tfidf = TfidfVectorizer(max_features=5000, ngram_range=(1, 2),
                        stop_words='english')

In [119]:
tfidf_matrix = tfidf.fit_transform(df['tags']).toarray()

In [122]:
tfidf_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(4803, 5000))

## Cosine Similarity

In [136]:
from sklearn.metrics.pairwise import cosine_similarity

In [142]:
def recommend_movies(title):
    # Get the index of the movie that matches the title
    idx = indices[title]
    
    # ✅ Fix: keep it 2D by using [idx:idx+1]
    sim_scores = cosine_similarity(tfidf_matrix[idx:idx+1], tfidf_matrix).flatten()
    
    # Get top 10 similar movies
    sim_indices = sim_scores.argsort()[-10-1:-1][::-1]
    return df['title'].iloc[sim_indices]

In [146]:
recommend_movies('Spectre')

3162                    Thunderball
1343          Never Say Never Again
11                Quantum of Solace
1200           The Living Daylights
4071          From Russia with Love
753                    The Sentinel
367                 The Interpreter
3351    The Man with the Golden Gun
29                          Skyfall
1717                     Safe Haven
Name: title, dtype: str

In [147]:
import pickle


pickle.dump(tfidf_matrix, open('tfidf_matrix.pkl', 'wb'))

pickle.dump(indices, open('indices.pkl', 'wb'))

df.to_pickle('df.pkl')

pickle.dump(tfidf, open('tfidf.pkl', 'wb'))